#!/usr/bin/perl
## Copyright (C) 2017 by Rohan Deshpande


sub total {
    my $total = 0;
    foreach (@_) {
        $total += $_;
    }
    $total;
}

sub average {
    my $total = &total(@_);
    my $len = @_;
    $total / $len;
}

sub above_average {
    my $average = &average(@_);
    my @results;
    foreach (@_) {
        if($_ > $average) {
            push(@results, $_);
        }
    }
    @results;
}

my @fred = &above_average(1..10);
print "\@fred is @fred\n";
print "(Should be 6 7 8 9 10)\n";
my @barney = &above_average(100, 1..10);
print "\@barney is @barney\n";
print "(Should be just 100)\n";
