#!/usr/bin/perl
my %family_name = (
  "Rohan" => "Deshpande",
  "Hannah" => "Montanez",
  "Ryan" => "Anderson",
  "Alex" => "Swope",
);

foreach(<STDIN>) {
  chomp($name = $_);
  print "$name\'s full name is $name $family_name{$name}\n";
}
