#!/usr/bin/perl
## Copyright (C) 2017 by Rohan Deshpande

$^I = ".bak";

while(<>) {
  s{## Copyright \(C\) 2017 by Rohan Deshpande\n}{};
  s{/usr/bin/perl$}{/usr/bin/perl\n## Copyright (C) 2017 by Rohan Deshpande\n};
  print;
}
