#!/usr/bin/perl
my @test = 1..20;
print "@test\n";
print (2+3) * 4;
print "\n";
print ((2+3) * 4);
print "\n";
my @items = qw( wilma dino pebbles );
my $format = "The items are:\n" . ("%10s\n" x @items);
printf $format, @items;
